development:
  adapter: postgresql
  encoding: unicode
  database: optimizer_development
  pool: 5
  timeout: 5000
  username: eaksyon
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: optimizer_test
  pool: 5
  timeout: 5000
  username: eaksyon
  password:
  host: localhost
  port: 5432

production:
  adapter: postgresql
  encoding: unicode
  database: optimizer_production
  pool: 5
  timeout: 5000
  username: eaksyon
  password:
