School.create!(title: "Mountain High School", students: 180, teachers: 13)
School.create!(title: "Long Island High School", students: 180, teachers: 13)
School.create!(title: "Another High School", students: 180, teachers: 13)
School.create!(title: "Test High School", students: 180, teachers: 13)
School.create!(title: "Some High School", students: 180, teachers: 13)
School.create!(title: "Another One High School", students: 180, teachers: 13)
