School.create!(title: "Mountain High School")
School.create!(title: "Long Island High School")
School.create!(title: "Another High School")
School.create!(title: "Test High School")
School.create!(title: "Some High School")
School.create!(title: "Another One High School")
